image: node:10

stages:
  - build

build_project:
  stage: build
  script:
    - cd src
    - npm install
    - npm run build
    - rm -rf chrome-extension
    - rm -rf node_modules
  artifacts:
    expire_in: 2 day
    paths:
    - dist

install_dependent:
  stage: build
  script:
    - ls -a
    - npm install --production
    - ls -a

