image: node:10

stages:
  - build-project
  - install-dependent

build_project:
  stage: build
  script:
    - cd src
    - npm install
    - npm run build
    - rm -rf chrome-extension
    - rm -rf node_modules
  artifacts:
    name: chromeExtension-dist
    expire_in: 2 day
    paths:
      - dist

install_dependent:
  stage: install-dependent
  dependencies:
    - chromeExtension-dist
  script:
    - ls -a
    - npm install --production
    - ls -a

