apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "helm.fullname" . }}
  labels:
    release: {{ .Release.Name }}
    appName: rebirth
    app: {{ template "helm.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        release: {{ .Release.Name }}
        appName: rebirth
        app: {{ template "helm.name" . }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      imagePullSecrets:
      - name: regsecret
      containers:
      - name: rebirth
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: IfNotPresent
        ports:
         - containerPort: {{ .Values.service.internalPort }}
        env:
        {{- range $key, $value := .Values.env }}
          - name: {{ $key }}
            value: {{ $value | replace "__string__" "" |  quote }}
        {{- end }}
        livenessProbe:
          initialDelaySeconds: 30
          timeoutSeconds: 5
          httpGet:
            port: 80
            path: /liveness
        resources:
          requests:
            cpu: 1000m
            memory: 1024Mi
          limits:
            cpu: 2000m
            memory: 2048Mi
