{{- $serviceName := include "helm.fullname" . -}}
{{- $servicePort := .Values.service.externalPort -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "helm.fullname" . }}
  labels:
    release: {{ .Release.Name }}
    appName: rebirth
    app: {{ template "helm.name" . }}
  annotations:
    app.gitlab.com/env: {{ .Values.env.CI_ENVIRONMENT_SLUG }}
    app.gitlab.com/app: {{ .Values.env.CI_PROJECT_PATH_SLUG }}
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
    {{- end }}
