apiVersion: v1
kind: Service
metadata:
  name: {{ template "helm.fullname" . }}
  labels:
    release: {{ .Release.Name }}
    appName: rebirth
    app: {{ template "helm.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    app: {{ template "helm.name" . }}
    release: {{ .Release.Name }}
