replicaCount: 3
terminationGracePeriodSeconds: 60
image:
  repository: rebirth
  tag: 0.0.1
env: &ENV
  MYSQL_HOST: ""
  MYSQL_PORT: ""
  MYSQL_USERNAME: ""
  MYSQL_PASSWORD: ""
  MYSQL_DATABASE: ""
  MYSQL_TABLE: ""
